export const SORT_SONGS   = 'App/SORT_SONGS'
export const FILTER_SONGS = 'App/FILTER_SONGS'

export const TABLE_HEADERS = [
  'Title',
  'Themes/key words',
  'Function/Emotion',
  'Writer',
  'Source',
  'Year',
  'Ideal Key(s)*',
  'Tempo',
  'Time',
  'Range',
  'Structure',
  'Style',
  'Difficulty (vocal)',
  'Addressed to',
  'I/we',
  'Driver'
];

export const SONGS = [
  {
    "Title": "All creatures of our God and king",
    "Themes/key words": "All creation praises",
    "Function/Emotion": "D: Praise, call to worship",
    "Writer": "St Francis, trad. /Crowder",
    "Source": "H",
    "Year": "C12th,17th",
    "Ideal Key(s)*": "Bb,B,C",
    "Tempo": 112,
    "Time": "6/4, 4/4",
    "Range": 8,
    "Structure": "V1,3,5,7",
    "Style": "Relaxed",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "All",
    "I/we": "We",
    "Driver": "P"
  },
  {
    "Title": "Amazing Grace",
    "Themes/key words": "Grace, fear, journey",
    "Function/Emotion": "D/R: Assurance",
    "Writer": "Newton,trad",
    "Source": "H",
    "Year": "1700s",
    "Ideal Key(s)*": "E,F",
    "Tempo": 92,
    "Time": "_,4/4",
    "Range": 8,
    "Structure": "V1-4",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Amazing Grace (My Chains)",
    "Themes/key words": "Grace, fear, journey",
    "Function/Emotion": "D/R: Assurance",
    "Writer": "Tomlin etc",
    "Source": "WT",
    "Year": 2006,
    "Ideal Key(s)*": "D",
    "Tempo": 120,
    "Time": "4/4",
    "Range": 11,
    "Structure": "vvcvvcc",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "And can it be",
    "Themes/key words": "Gospel, freedom, righteousness",
    "Function/Emotion": "D/R: Assurance, boldness",
    "Writer": "Wesley, Campbell",
    "Source": "H",
    "Year": 1738,
    "Ideal Key(s)*": "F",
    "Tempo": 144,
    "Time": "4/4",
    "Range": 10,
    "Structure": "V1,3,4,5",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "All, God",
    "I/we": "I",
    "Driver": "P"
  },
  {
    "Title": "Be still my soul",
    "Themes/key words": "Grief, trust, guidance, sovereignty",
    "Function/Emotion": "P/R: Comfort",
    "Writer": "Schlegel, Sibelius",
    "Source": "H",
    "Year": "1800s",
    "Ideal Key(s)*": "D, Eb",
    "Tempo": 92,
    "Time": "4/4",
    "Range": 6,
    "Structure": "V1-4",
    "Style": "Reflective",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Self",
    "I/we": "I",
    "Driver": "P"
  },
  {
    "Title": "Be thou my vision",
    "Themes/key words": "Vision, wisdom, wealth, victory, shelter",
    "Function/Emotion": "R: (Pledge)",
    "Writer": "Trad.",
    "Source": "H",
    "Year": "1800s",
    "Ideal Key(s)*": "D",
    "Tempo": 92,
    "Time": "3/4",
    "Range": 11,
    "Structure": "V1-5",
    "Style": "Celtic",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Come thou fount",
    "Themes/key words": "Praise, grace, faithfulness, wandering",
    "Function/Emotion": "D: Praise, P/R: (Pledge)",
    "Writer": "Robinson, Wyeth",
    "Source": "H",
    "Year": "1700s",
    "Ideal Key(s)*": "Bb,B,C",
    "Tempo": 72,
    "Time": "3/4",
    "Range": 8,
    "Structure": "V1-4",
    "Style": "Relaxed",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Crown him",
    "Themes/key words": "King of humanity, love, life, peace, time",
    "Function/Emotion": "D/R: Praise of Jesus",
    "Writer": "Elvey, Bridges",
    "Source": "H",
    "Year": "1800s",
    "Ideal Key(s)*": "Bb,C,D",
    "Tempo": 104,
    "Time": "4/4",
    "Range": 8,
    "Structure": "V1,2,3,4,6",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All, self",
    "I/we": "I, we",
    "Driver": "P"
  },
  {
    "Title": "God has spoken",
    "Themes/key words": "God�s word, Spirit, Trinity, spoken in history",
    "Function/Emotion": "D/P: Reminder",
    "Writer": "Briggs, Beethoven",
    "Source": "H",
    "Year": "1800s",
    "Ideal Key(s)*": "E,F",
    "Tempo": 96,
    "Time": "4/4",
    "Range": 8,
    "Structure": "V1,2,3",
    "Style": "Straight",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Church",
    "I/we": "We",
    "Driver": "P"
  },
  {
    "Title": "Great is your faithfulness",
    "Themes/key words": "Provision, guidance, faithfulness",
    "Function/Emotion": "R: Thankfulness",
    "Writer": "Chisholm, Runyan",
    "Source": "H",
    "Year": 1923,
    "Ideal Key(s)*": "Bb, C",
    "Tempo": 92,
    "Time": "3/4",
    "Range": 8,
    "Structure": "VCVCVC",
    "Style": "Straight",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG*"
  },
  {
    "Title": "Here is Love",
    "Themes/key words": "Cross, love, grace, mercy, justice",
    "Function/Emotion": "R: Thankfulness, obedience",
    "Writer": "Rees, Lowry",
    "Source": "H",
    "Year": 1876,
    "Ideal Key(s)*": "E, F",
    "Tempo": 80,
    "Time": "3/4",
    "Range": 8,
    "Structure": "V1-3",
    "Style": "Relaxed",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God, others",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Holy holy holy",
    "Themes/key words": "Worship, glory, trinity",
    "Function/Emotion": "D: Attributes of God",
    "Writer": "Heber, Dykes",
    "Source": "H",
    "Year": "1800s",
    "Ideal Key(s)*": "Bb,C",
    "Tempo": 88,
    "Time": "4/4",
    "Range": 8,
    "Structure": "V1,3,4",
    "Style": "Straight",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "",
    "Themes/key words": "",
    "Function/Emotion": "",
    "Writer": "",
    "Source": "",
    "Year": "",
    "Ideal Key(s)*": "",
    "Tempo": "",
    "Time": "",
    "Range": "",
    "Structure": "",
    "Style": "",
    "Difficulty (vocal)": "",
    "Addressed to": "",
    "I/we": "",
    "Driver": ""
  },
  {
    "Title": "How great thou art",
    "Themes/key words": "God�s goodness; creation, atonement, Jesus return",
    "Function/Emotion": "D/R: Praise, thankfulness",
    "Writer": "Boberg, Hine",
    "Source": "H",
    "Year": "1800s",
    "Ideal Key(s)*": "G",
    "Tempo": 112,
    "Time": "4/4",
    "Range": 10,
    "Structure": "V1,C,V3,C,V4,C",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "God, others",
    "I/we": "I",
    "Driver": "PG*"
  },
  {
    "Title": "I cannot tell",
    "Themes/key words": "Story of Jesus, Saviour/King",
    "Function/Emotion": "D/R: Joy in Jesus Saviour of all",
    "Writer": "Fullerton, trad",
    "Source": "H",
    "Year": 1929,
    "Ideal Key(s)*": "C",
    "Tempo": 104,
    "Time": "4/4",
    "Range": 12,
    "Structure": "V1-4",
    "Style": "Celtic",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "Any",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "It is well",
    "Themes/key words": "Sorrow, atonement, hope, J�s return",
    "Function/Emotion": "R: Assurance, comfort, hope",
    "Writer": "Spafford, Bliss",
    "Source": "H",
    "Year": "1800s",
    "Ideal Key(s)*": "A, Bb",
    "Tempo": 92,
    "Time": "4/4",
    "Range": 8,
    "Structure": "V1CV2CV3CV5/6C",
    "Style": "Emotional",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Any",
    "I/we": "I",
    "Driver": "PG*"
  },
  {
    "Title": "Jesus paid it all",
    "Themes/key words": "Weakness, trust, forgiveness, transformation",
    "Function/Emotion": "R: Assurance, trust, strength",
    "Writer": "Hall, Grape",
    "Source": "H",
    "Year": 1865,
    "Ideal Key(s)*": "C",
    "Tempo": 72,
    "Time": "3/4",
    "Range": 8,
    "Structure": "V1-4",
    "Style": "Varies",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Any",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Just as I am (old)",
    "Themes/key words": "Grace in sin, fear, doubt, atonement",
    "Function/Emotion": "P/R: Dependence, confession",
    "Writer": "Elliot,Bradbury",
    "Source": "H",
    "Year": "C19th",
    "Ideal Key(s)*": "C",
    "Tempo": 92,
    "Time": "3/4",
    "Range": 8,
    "Structure": "V1,3,4",
    "Style": "Relaxed",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Just as I am (new)",
    "Themes/key words": "",
    "Function/Emotion": "",
    "Writer": "Bargerbos",
    "Source": "Exalt",
    "Year": 2014,
    "Ideal Key(s)*": "F#m/A",
    "Tempo": 100,
    "Time": "3/4",
    "Range": 11,
    "Structure": "VVCVCC",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Man of Sorrows (old)",
    "Themes/key words": "Saviour, cross, atonement, king",
    "Function/Emotion": "R: Sorrow and joy of cross",
    "Writer": "Bliss",
    "Source": "H",
    "Year": 1875,
    "Ideal Key(s)*": "G, A",
    "Tempo": 76,
    "Time": "4/4",
    "Range": 8,
    "Structure": "V1-5",
    "Style": "Straight",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "Each other",
    "I/we": "I, we",
    "Driver": "P"
  },
  {
    "Title": "May the mind (old)",
    "Themes/key words": "Obedience: mind, word, peace, love, race",
    "Function/Emotion": "R: Obedience",
    "Writer": "Gould,Wilkinsn",
    "Source": "H",
    "Year": 1913,
    "Ideal Key(s)*": "C",
    "Tempo": 96,
    "Time": "4/4",
    "Range": 9,
    "Structure": "V1-5",
    "Style": "Straight",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "P"
  },
  {
    "Title": "May the mind (new)",
    "Themes/key words": "",
    "Function/Emotion": "",
    "Writer": "Peterson",
    "Source": "Emu",
    "Year": 1994,
    "Ideal Key(s)*": "D,E",
    "Tempo": 120,
    "Time": "4/4",
    "Range": 6,
    "Structure": "",
    "Style": "Relaxed",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "",
    "I/we": "",
    "Driver": "PG"
  },
  {
    "Title": "My hope is built (old)",
    "Themes/key words": "Hope, grace, merit, steadfastness",
    "Function/Emotion": "D/R: Sure hope in uncertainty of life",
    "Writer": "Mote, Bradbury",
    "Source": "H",
    "Year": 1834,
    "Ideal Key(s)*": "E",
    "Tempo": 80,
    "Time": "3/4",
    "Range": 9,
    "Structure": "V1-4",
    "Style": "Straight",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "P"
  },
  {
    "Title": "My hope is built (new",
    "Themes/key words": "",
    "Function/Emotion": "",
    "Writer": "Chiswell",
    "Source": "Emu",
    "Year": 1992,
    "Ideal Key(s)*": "D",
    "Tempo": 120,
    "Time": "4/4",
    "Range": 11,
    "Structure": "",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Hard",
    "Addressed to": "",
    "I/we": "",
    "Driver": "PG"
  },
  {
    "Title": "O for 1000 (old)",
    "Themes/key words": "Life of Jesus, joyful praise, declaration of goodness",
    "Function/Emotion": "D: Joyful praise",
    "Writer": "Wesley, Jarman",
    "Source": "H",
    "Year": "C18th",
    "Ideal Key(s)*": "E,F",
    "Tempo": 132,
    "Time": "4/4",
    "Range": 9,
    "Structure": "V1-6",
    "Style": "Straight",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "O for 1000 (new)",
    "Themes/key words": "",
    "Function/Emotion": "R: Proclamation",
    "Writer": "Crowder?",
    "Source": "H",
    "Year": "",
    "Ideal Key(s)*": "E,F",
    "Tempo": 112,
    "Time": "3/4",
    "Range": 8,
    "Structure": "",
    "Style": "Relaxed",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "",
    "I/we": "",
    "Driver": ""
  },
  {
    "Title": "Praise to the Lord",
    "Themes/key words": "Praise, church, sustains, shelter",
    "Function/Emotion": "D: Call to worship",
    "Writer": "Neander, Winkworth",
    "Source": "H",
    "Year": "C19th",
    "Ideal Key(s)*": "Eb,E",
    "Tempo": 132,
    "Time": "3/4",
    "Range": 9,
    "Structure": "V1,2,3,5",
    "Style": "Straight",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Self, church",
    "I/we": "I, we",
    "Driver": "PG*"
  },
  {
    "Title": "Rock of ages (old)",
    "Themes/key words": "Guilt, judgment, grace, mercy",
    "Function/Emotion": "P, R: Confession, absolution",
    "Writer": "Toplady",
    "Source": "H",
    "Year": "C18th,?",
    "Ideal Key(s)*": "G",
    "Tempo": 72,
    "Time": "3/4",
    "Range": 8,
    "Structure": "V1-4",
    "Style": "Straight",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "P?G"
  },
  {
    "Title": "Rock of Ages (new)",
    "Themes/key words": "",
    "Function/Emotion": "",
    "Writer": "Buchanan",
    "Source": "AFES",
    "Year": "",
    "Ideal Key(s)*": "Bb,B",
    "Tempo": 60,
    "Time": "6/8",
    "Range": 10,
    "Structure": "V1-4",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "",
    "I/we": "",
    "Driver": ""
  },
  {
    "Title": "Take my life (old)",
    "Themes/key words": "Obedience; service, speech, money, mind, love",
    "Function/Emotion": "R: Obedience, surrender?",
    "Writer": "Havergal,",
    "Source": "H",
    "Year": "C19th, ?",
    "Ideal Key(s)*": "F",
    "Tempo": 100,
    "Time": "3/4",
    "Range": 8,
    "Structure": "V1-6",
    "Style": "Straight",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "P"
  },
  {
    "Title": "Take my life (new)",
    "Themes/key words": "",
    "Function/Emotion": "",
    "Writer": "Buchanan",
    "Source": "AFES",
    "Year": "",
    "Ideal Key(s)*": "C",
    "Tempo": 72,
    "Time": "4/4",
    "Range": 8,
    "Structure": "V1-6",
    "Style": "Reflective",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "",
    "I/we": "",
    "Driver": ""
  },
  {
    "Title": "Thine be the glory",
    "Themes/key words": "Resurrection, victory",
    "Function/Emotion": "D: Confidence through death",
    "Writer": "Budry, Handel",
    "Source": "H",
    "Year": "C18th",
    "Ideal Key(s)*": "D",
    "Tempo": 100,
    "Time": "4/4",
    "Range": 9,
    "Structure": "V1-3",
    "Style": "Straight",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "God",
    "I/we": "We",
    "Driver": "P"
  },
  {
    "Title": "To God be the glory",
    "Themes/key words": "Victory over death, resurrection",
    "Function/Emotion": "D: Victory, hope",
    "Writer": "Crosby, Doane",
    "Source": "H",
    "Year": 1875,
    "Ideal Key(s)*": "F, G",
    "Tempo": 104,
    "Time": "3/4",
    "Range": 8,
    "Structure": "VCVCVC",
    "Style": "Straight",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "P"
  },
  {
    "Title": "What a friend",
    "Themes/key words": "Prayer, friend, refuge, solace",
    "Function/Emotion": "D/R: Comfort, refuge",
    "Writer": "Scriven, Converse",
    "Source": "H",
    "Year": 1868,
    "Ideal Key(s)*": "E",
    "Tempo": 84,
    "Time": "4/4",
    "Range": 9,
    "Structure": "V1-3",
    "Style": "Relaxed",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "PG*"
  },
  {
    "Title": "When I survey",
    "Themes/key words": "Cross, sacrifice, love",
    "Function/Emotion": "R: Thankfulness, response to love",
    "Writer": "Watts, Miller",
    "Source": "H",
    "Year": "C18th",
    "Ideal Key(s)*": "C",
    "Tempo": 88,
    "Time": "3/4",
    "Range": 8,
    "Structure": "V1-4",
    "Style": "Straight,reflective",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "-",
    "I/we": "I",
    "Driver": "PG*"
  },
  {
    "Title": "Come people of the risen king",
    "Themes/key words": "Unity, church, praise",
    "Function/Emotion": "D: Call to worship, invitation",
    "Writer": "Townend, Getty",
    "Source": "Thankyou",
    "Year": 2007,
    "Ideal Key(s)*": "Bb",
    "Tempo": 108,
    "Time": "4/4",
    "Range": 11,
    "Structure": "VCVCVC",
    "Style": "Upbeat, driving",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "How deep the F�s love",
    "Themes/key words": "Cross, atonement, love, (boasting)",
    "Function/Emotion": "R: Repentance, thankfulness",
    "Writer": "Townend",
    "Source": "Thankyou",
    "Year": 1995,
    "Ideal Key(s)*": "Eb,E,F",
    "Tempo": 108,
    "Time": "5/4",
    "Range": 8,
    "Structure": "V1-3",
    "Style": "Slow, reflective",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Each other",
    "I/we": "We/I",
    "Driver": "PG"
  },
  {
    "Title": "In Christ Alone",
    "Themes/key words": "Incarnation, atonement, resurrection, future",
    "Function/Emotion": "D/P: Assurance, hope",
    "Writer": "Townend, Getty",
    "Source": "Thankyou",
    "Year": 2001,
    "Ideal Key(s)*": "D,Eb",
    "Tempo": 60,
    "Time": "3/4",
    "Range": 11,
    "Structure": "V1-4",
    "Style": "Celtic",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "O church arise",
    "Themes/key words": "Church, battle, love, faith, strength, glory, victory",
    "Function/Emotion": "D/R: Call to worship, perseverance, victory",
    "Writer": "Townend, Getty",
    "Source": "Thankyou",
    "Year": 2005,
    "Ideal Key(s)*": "D",
    "Tempo": 58,
    "Time": "3/4",
    "Range": 11,
    "Structure": "V1-4",
    "Style": "Celtic",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "Resurrection hymn",
    "Themes/key words": "Resurrection of Jesus and his people",
    "Function/Emotion": "D/R: Assurance, victory, hope",
    "Writer": "Townend, Getty",
    "Source": "Thankyou",
    "Year": 2003,
    "Ideal Key(s)*": "D",
    "Tempo": 92,
    "Time": "12/8",
    "Range": 11,
    "Structure": "V1-3",
    "Style": "Lilting",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "All",
    "I/we": "We",
    "Driver": "P"
  },
  {
    "Title": "Speak O Lord",
    "Themes/key words": "Word, truth, obedience, humility",
    "Function/Emotion": "P: Prep for word, obedience",
    "Writer": "Townend, Getty",
    "Source": "Thankyou",
    "Year": 2005,
    "Ideal Key(s)*": "Bb,B,C",
    "Tempo": 72,
    "Time": "4/4",
    "Range": 8,
    "Structure": "V1-3",
    "Style": "Reflective",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God",
    "I/we": "We",
    "Driver": "P"
  },
  {
    "Title": "The perfect wisdom",
    "Themes/key words": "Wisdom in creation, salvation and life",
    "Function/Emotion": "P/R: Reflection, assurance, comfort",
    "Writer": "Townend, Getty",
    "Source": "Thankyou",
    "Year": 2011,
    "Ideal Key(s)*": "Bb",
    "Tempo": 68,
    "Time": "3/4",
    "Range": 9,
    "Structure": "V1-3",
    "Style": "Reflective",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "All",
    "I/we": "We",
    "Driver": "P"
  },
  {
    "Title": "The power of the cross",
    "Themes/key words": "Cross, forgiveness, atonement, resurrection",
    "Function/Emotion": "D/R: Confession, absolution, thanksgiving",
    "Writer": "Townend, Getty",
    "Source": "Thankyou",
    "Year": 2005,
    "Ideal Key(s)*": "Bb",
    "Tempo": 76,
    "Time": "4/4",
    "Range": 9,
    "Structure": "VCVCVCVC",
    "Style": "Refective, moderate",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "All",
    "I/we": "We",
    "Driver": "P"
  },
  {
    "Title": "Hear our prayer",
    "Themes/key words": "Prayer, faith, kingdom come, seeking God",
    "Function/Emotion": "R: Pleading, expression of faith",
    "Writer": "Cooper, Judd",
    "Source": "Emu",
    "Year": 2014,
    "Ideal Key(s)*": "Bb",
    "Tempo": 68,
    "Time": "4/4",
    "Range": 11,
    "Structure": "VVCVCC",
    "Style": "Reflective",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "God",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "Lift up your heads",
    "Themes/key words": "Jesus as returning King, leads his people in glory",
    "Function/Emotion": "D: Joy in Jesus�s victory, return",
    "Writer": "Morrow",
    "Source": "Emu",
    "Year": 2007,
    "Ideal Key(s)*": "F,G",
    "Tempo": 57,
    "Time": "6/8",
    "Range": 8,
    "Structure": "VCVCVC",
    "Style": "Moderate, driving",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "All",
    "I/we": "They",
    "Driver": "G"
  },
  {
    "Title": "Never Alone",
    "Themes/key words": "God come near in Jesus�s death and resurrection",
    "Function/Emotion": "R: Joy and security in Jesus",
    "Writer": "Richardson, Percival",
    "Source": "Emu",
    "Year": 2006,
    "Ideal Key(s)*": "C,D,E",
    "Tempo": 84,
    "Time": "4/4",
    "Range": 6,
    "Structure": "V1-4",
    "Style": "Moderate",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "No other name",
    "Themes/key words": "Salvation, strength, joy, victory only in Jesus",
    "Function/Emotion": "D/R: Joy and hope in Jesus�s salvation",
    "Writer": "Hodge",
    "Source": "Emu",
    "Year": 2010,
    "Ideal Key(s)*": "Bb",
    "Tempo": 65,
    "Time": "4/4",
    "Range": 11,
    "Structure": "VCVCVC",
    "Style": "Moderate, driving",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "Both",
    "I/we": "I/we",
    "Driver": "P"
  },
  {
    "Title": "Psalm 96",
    "Themes/key words": "God worthy of worship as saviour and judge",
    "Function/Emotion": "D: Worship, declaration",
    "Writer": "McDonald",
    "Source": "Emu",
    "Year": 1987,
    "Ideal Key(s)*": "D, E",
    "Tempo": 84,
    "Time": "4/4",
    "Range": 9,
    "Structure": "VVCVCC",
    "Style": "Relaxed",
    "Difficulty (vocal)": "Mod",
    "Addressed to": "All",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "See him coming",
    "Themes/key words": "Praise of Jesus as living and returning King",
    "Function/Emotion": "D: Praise of Jesus, anticipating his return",
    "Writer": "Peterson",
    "Source": "Emu",
    "Year": 2003,
    "Ideal Key(s)*": "C",
    "Tempo": 92,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VVCVCBC",
    "Style": "Driving",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "The Chorus of the Saved",
    "Themes/key words": "Praise, salvation, drawing near",
    "Function/Emotion": "D: Call to praise Jesus",
    "Writer": "Hodge",
    "Source": "Emu",
    "Year": 2014,
    "Ideal Key(s)*": "Bb",
    "Tempo": 100,
    "Time": "4/4",
    "Range": 11,
    "Structure": "VVCVCBC",
    "Style": "Upbeat",
    "Difficulty (vocal)": "Big range",
    "Addressed to": "All",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "The Day will come",
    "Themes/key words": "Jesus�s return",
    "Function/Emotion": "D: Personal knowledge of returning saviour",
    "Writer": "Peterson",
    "Source": "Emu",
    "Year": 2007,
    "Ideal Key(s)*": "Am",
    "Tempo": 88,
    "Time": "4/4",
    "Range": 10,
    "Structure": "VCVCC",
    "Style": "Atmospheric",
    "Difficulty (vocal)": "Syncopated",
    "Addressed to": "All",
    "I/we": "We/I",
    "Driver": "PG"
  },
  {
    "Title": "This life I live",
    "Themes/key words": "Sin, repentance, salvation",
    "Function/Emotion": "R: Obedience, living for Jesus not self",
    "Writer": "Morrow",
    "Source": "Emu",
    "Year": 2009,
    "Ideal Key(s)*": "Bb,B,C",
    "Tempo": 68,
    "Time": "3/4",
    "Range": 8,
    "Structure": "VVV",
    "Style": "Reflective",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Self, all",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "We belong to the day",
    "Themes/key words": "Jesus return, light, judgement, salvation, evangelism, bride",
    "Function/Emotion": "D/R: Sober judgment, mission, salvation",
    "Writer": "Morrow",
    "Source": "Emu",
    "Year": 2006,
    "Ideal Key(s)*": "C#m/E",
    "Tempo": 124,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VVCVCBC",
    "Style": "Upbeat",
    "Difficulty (vocal)": "Syncopated",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "City on a hill",
    "Themes/key words": "Beatitudes, salt and light, Kingdom, Spirit, humility",
    "Function/Emotion": "D/R: God�s kingdom and light in the merciful",
    "Writer": "S Robinson, R Shiner",
    "Source": "Exalt",
    "Year": 2014,
    "Ideal Key(s)*": "Em/G",
    "Tempo": 96,
    "Time": "4/4",
    "Range": 9,
    "Structure": "VCVCC",
    "Style": "Slow but driving",
    "Difficulty (vocal)": "Moderate",
    "Addressed to": "All",
    "I/we": "We/they",
    "Driver": "PG"
  },
  {
    "Title": "Come you thirsty",
    "Themes/key words": "Contentment, trust, comfort",
    "Function/Emotion": "R: Comfort, trust, assurance, need",
    "Writer": "L Gordon",
    "Source": "Exalt",
    "Year": 2012,
    "Ideal Key(s)*": "Bb,B,C",
    "Tempo": 84,
    "Time": "3/4",
    "Range": 8,
    "Structure": "VVVV",
    "Style": "Slow, celtic",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Self, each other",
    "I/we": "We",
    "Driver": "P"
  },
  {
    "Title": "Forever Faithful",
    "Themes/key words": "Sin, guidance, trust, idols, mercy",
    "Function/Emotion": "R: Confession, expression of trust",
    "Writer": "S Robinson",
    "Source": "Exalt",
    "Year": 2013,
    "Ideal Key(s)*": "C",
    "Tempo": 50,
    "Time": "6/8",
    "Range": 10,
    "Structure": "VCVCC",
    "Style": "Reflective, lilting",
    "Difficulty (vocal)": "Moderate",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Hail the King",
    "Themes/key words": "Jesus fulfilment of OT, king, justice, nations",
    "Function/Emotion": "D/R: Praise, declaration of Jesus God�s king",
    "Writer": "L Gordon",
    "Source": "Exalt",
    "Year": 2012,
    "Ideal Key(s)*": "F",
    "Tempo": 70,
    "Time": "6/8",
    "Range": 8,
    "Structure": "VCVCC",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Moderate",
    "Addressed to": "All",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "Just as I am",
    "Themes/key words": "Mercy, sin, atonement, cleansing",
    "Function/Emotion": "D/R: Expression of trust in Jesus�s mercy",
    "Writer": "J Bargerbos",
    "Source": "Exalt",
    "Year": 2014,
    "Ideal Key(s)*": "F#m/A",
    "Tempo": 100,
    "Time": "3/4",
    "Range": 11,
    "Structure": "VVCVCC",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Moderate",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Merciful God",
    "Themes/key words": "Confession, forgiveness, cleansing, obedience",
    "Function/Emotion": "P: Confession, prayer",
    "Writer": "L Gordon",
    "Source": "Exalt",
    "Year": 2010,
    "Ideal Key(s)*": "Bb",
    "Tempo": 126,
    "Time": "3/4",
    "Range": 11,
    "Structure": "VCVC",
    "Style": "Reflective",
    "Difficulty (vocal)": "Moderate",
    "Addressed to": "God",
    "I/we": "We",
    "Driver": "P"
  },
  {
    "Title": "One heart, one people",
    "Themes/key words": "Unity, church, gathering",
    "Function/Emotion": "D: Expression of unity in gathering",
    "Writer": "L Gordon",
    "Source": "Exalt",
    "Year": 2016,
    "Ideal Key(s)*": "F,G",
    "Tempo": 108,
    "Time": "4/4",
    "Range": 6,
    "Structure": "VCVCBC",
    "Style": "Upbeat, opener",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "Onwards & Upwards",
    "Themes/key words": "Philippians, continuing in faith, evangelism",
    "Function/Emotion": "D: Encouraging each other to continue",
    "Writer": "L Gordon",
    "Source": "Exalt",
    "Year": 2007,
    "Ideal Key(s)*": "F,G",
    "Tempo": 96,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VVCVVCBC",
    "Style": "Upbeat",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "Waiting for the day",
    "Themes/key words": "Jesus return, faith and sight, meeting Jesus, trust",
    "Function/Emotion": "R: Expression of desire to meet Jesus, comfort",
    "Writer": "L Gordon",
    "Source": "Exalt",
    "Year": 2009,
    "Ideal Key(s)*": "D",
    "Tempo": 84,
    "Time": "2/2",
    "Range": 9,
    "Structure": "VCVCBC",
    "Style": "Reflective, uplifting",
    "Difficulty (vocal)": "Moderate",
    "Addressed to": "God, each other",
    "I/we": "I/we",
    "Driver": "P"
  },
  {
    "Title": "All I have is Christ",
    "Themes/key words": "Sin, faith atonement, obedience",
    "Function/Emotion": "D/R: Expression of faith and obedience",
    "Writer": "J Kauflin",
    "Source": "SG",
    "Year": 2008,
    "Ideal Key(s)*": "C",
    "Tempo": 76,
    "Time": "3/4",
    "Range": 10,
    "Structure": "VCVCVC",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Moderate",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Before the throne",
    "Themes/key words": "Grace, atonement, election, judgment, resurrection",
    "Function/Emotion": "D/R: Thankfulness for forgiveness, joy in assurance",
    "Writer": "Bancroft, Cook",
    "Source": "SG",
    "Year": 1997,
    "Ideal Key(s)*": "C, D",
    "Tempo": 76,
    "Time": "3/4",
    "Range": 12,
    "Structure": "VVV",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Mod (range)",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Behold our God",
    "Themes/key words": "God alone as creator, ruler and redeemer",
    "Function/Emotion": "D: Characteristics of God",
    "Writer": "Baird, Altrogge",
    "Source": "SG",
    "Year": 2011,
    "Ideal Key(s)*": "C",
    "Tempo": 73,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VCVCVC(BC)",
    "Style": "Slow, uplifting",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All, each other",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "Come you saints",
    "Themes/key words": "Election, grace, salvation, heaven",
    "Function/Emotion": "D: Reason to gather, expression of unity",
    "Writer": "Baird",
    "Source": "SG",
    "Year": 2004,
    "Ideal Key(s)*": "E, F",
    "Tempo": 64,
    "Time": "6/8",
    "Range": 9,
    "Structure": "VVV",
    "Style": "Opener",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "I have a shelter",
    "Themes/key words": "Shelter, rest, peace, trials, refuge, weakness",
    "Function/Emotion": "D/R: Expression of dependence",
    "Writer": "B Kauflin, Cook",
    "Source": "SG",
    "Year": 2008,
    "Ideal Key(s)*": "C",
    "Tempo": 76,
    "Time": "3/4",
    "Range": 10,
    "Structure": "VVV",
    "Style": "Reflective",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Jesus",
    "I/we": "I",
    "Driver": "P"
  },
  {
    "Title": "Jesus thank you",
    "Themes/key words": "Forgiveness, thanksgiving, grace",
    "Function/Emotion": "D/R: Thanksgiving for forgiveness",
    "Writer": "P Sczebel",
    "Source": "SG",
    "Year": 2003,
    "Ideal Key(s)*": "G",
    "Tempo": 130,
    "Time": "4/4",
    "Range": 11,
    "Structure": "VCVCBC",
    "Style": "Pledge",
    "Difficulty (vocal)": "Mod (rhythm, range)",
    "Addressed to": "Jesus",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Let your kingdom come",
    "Themes/key words": "Evangelism, kingdom, mission, grace",
    "Function/Emotion": "D/R: Prayer for action",
    "Writer": "B Kauflin",
    "Source": "SG",
    "Year": 2006,
    "Ideal Key(s)*": "F,G",
    "Tempo": 120,
    "Time": "4/4",
    "Range": 10,
    "Structure": "VCVCC",
    "Style": "Upbeat, inspiring",
    "Difficulty (vocal)": "Mod (pitch, rhythm)",
    "Addressed to": "God",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "O Great God",
    "Themes/key words": "Sin, Spirit, gospel, obedience",
    "Function/Emotion": "R: Thanksgiving for salvation, prayer for obedience",
    "Writer": "B Kauflin",
    "Source": "SG",
    "Year": 2006,
    "Ideal Key(s)*": "C",
    "Tempo": 72,
    "Time": "3/4",
    "Range": 10,
    "Structure": "VVV",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "P"
  },
  {
    "Title": "Refuge",
    "Themes/key words": "",
    "Function/Emotion": "",
    "Writer": "",
    "Source": "",
    "Year": "",
    "Ideal Key(s)*": "",
    "Tempo": "",
    "Time": "",
    "Range": "",
    "Structure": "",
    "Style": "",
    "Difficulty (vocal)": "",
    "Addressed to": "",
    "I/we": "",
    "Driver": ""
  },
  {
    "Title": "Grace Alone",
    "Themes/key words": "Grace not works, election, new creation",
    "Function/Emotion": "D: Reminder of grace",
    "Writer": "Kensrue",
    "Source": "MH",
    "Year": 2013,
    "Ideal Key(s)*": "D",
    "Tempo": 144,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VCVCBC",
    "Style": "Upbeat",
    "Difficulty (vocal)": "Syncopated",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "G"
  },
  {
    "Title": "Cornerstone",
    "Themes/key words": "Grace in present and future, darkness",
    "Function/Emotion": "D: Expression of trust in Jesus",
    "Writer": "Myrin et al",
    "Source": "HS",
    "Year": 2011,
    "Ideal Key(s)*": "C,D",
    "Tempo": 72,
    "Time": "4/4",
    "Range": "6-Dec",
    "Structure": "VVCVCVC",
    "Style": "Reflective",
    "Difficulty (vocal)": "Moderate",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Desert song",
    "Themes/key words": "Trials, dryness, provision, refining, praise",
    "Function/Emotion": "D/R: Joy and worship despite trials",
    "Writer": "Ligertwood",
    "Source": "HS",
    "Year": 2008,
    "Ideal Key(s)*": "D",
    "Tempo": 120,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VVCVCBV",
    "Style": "Moderate",
    "Difficulty (vocal)": "Mod (rhythm)",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "G"
  },
  {
    "Title": "For all you�ve done",
    "Themes/key words": "Redemption, joy",
    "Function/Emotion": "D: Opener",
    "Writer": "Morgan",
    "Source": "HS",
    "Year": 2004,
    "Ideal Key(s)*": "E",
    "Tempo": 132,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VPCVPCPC",
    "Style": "Upbeat",
    "Difficulty (vocal)": "Mod (rhythm)",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "G"
  },
  {
    "Title": "Man of sorrows",
    "Themes/key words": "Cross, salvation, sacrifice, atonement, praise",
    "Function/Emotion": "D/R: Honour of Jesus�s sacrifice",
    "Writer": "Ligertwood, Crocker",
    "Source": "HS",
    "Year": 2012,
    "Ideal Key(s)*": "Bb,B,C",
    "Tempo": 80,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VVCVCBVC",
    "Style": "Moving",
    "Difficulty (vocal)": "Easy (not structure)",
    "Addressed to": "All/God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Mighty to save",
    "Themes/key words": "Forgiveness, surrender, salvation",
    "Function/Emotion": "D: General",
    "Writer": "Morgan, Fielding",
    "Source": "HS",
    "Year": 2006,
    "Ideal Key(s)*": "F,G",
    "Tempo": 76,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VCVCBC",
    "Style": "Moderate, builds",
    "Difficulty (vocal)": "Mod (rhythm)",
    "Addressed to": "Any",
    "I/we": "I",
    "Driver": "G"
  },
  {
    "Title": "O praise the name",
    "Themes/key words": "Jesus death, resurrection and return",
    "Function/Emotion": "D: Praise and declaration of gospel",
    "Writer": "Sampson et al",
    "Source": "HS",
    "Year": 2015,
    "Ideal Key(s)*": "G",
    "Tempo": 72,
    "Time": "4/4",
    "Range": 12,
    "Structure": "VVCVCVC",
    "Style": "Slow, builds",
    "Difficulty (vocal)": "(rhythm, range)",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "This I Believe",
    "Themes/key words": "Creation, gospel, trinity",
    "Function/Emotion": "D: Declaration of faith",
    "Writer": "Crocker, Fielding",
    "Source": "HS",
    "Year": 2014,
    "Ideal Key(s)*": "F,G",
    "Tempo": 76,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VCVCBCC",
    "Style": "Slow, builds",
    "Difficulty (vocal)": "Mod (rhythm)",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "This is our God",
    "Themes/key words": "God�s love, dependence, worship, gospel",
    "Function/Emotion": "D/R: Prayer for help, worship, dependence",
    "Writer": "Morgan",
    "Source": "HS",
    "Year": 2008,
    "Ideal Key(s)*": "E",
    "Tempo": 76,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VCVCBC",
    "Style": "Reflective",
    "Difficulty (vocal)": "Mod (rhythm)",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "What the Lord has done in me",
    "Themes/key words": "Conversion, weakness, cleansing, declaration",
    "Function/Emotion": "D: Praise and declaration of gospel",
    "Writer": "Morgan",
    "Source": "HS",
    "Year": 1998,
    "Ideal Key(s)*": "C",
    "Tempo": 70,
    "Time": "3/4",
    "Range": 10,
    "Structure": "VVCVVC",
    "Style": "Slow",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Even So Come",
    "Themes/key words": "Return of Jesus, church as bride, ready and waiting",
    "Function/Emotion": "D/R: Pledge to be ready for Jesus",
    "Writer": "Tomlin et al",
    "Source": "WT",
    "Year": 2015,
    "Ideal Key(s)*": "D",
    "Tempo": 54,
    "Time": "6/8",
    "Range": 11,
    "Structure": "VVCVCBC",
    "Style": "Uplifting",
    "Difficulty (vocal)": "(Rhythm, range)",
    "Addressed to": "All/God",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "Forever",
    "Themes/key words": "God�s love, thanks, praise",
    "Function/Emotion": "D: Praise for God�s love and salvation",
    "Writer": "Tomlin",
    "Source": "WT",
    "Year": 2001,
    "Ideal Key(s)*": "E",
    "Tempo": 140,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VVCVCC",
    "Style": "Upbeat",
    "Difficulty (vocal)": "Rhythm, scanning",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "How great is our God",
    "Themes/key words": "Characteristics of God: light, trinity, majesty, kingship",
    "Function/Emotion": "D: Expression of God�s character",
    "Writer": "Tomlin, Reeves",
    "Source": "WT",
    "Year": 2004,
    "Ideal Key(s)*": "G",
    "Tempo": 80,
    "Time": "4/4",
    "Range": 9,
    "Structure": "VCVCBC",
    "Style": "Reflective, uplifting",
    "Difficulty (vocal)": "Rhythm",
    "Addressed to": "All",
    "I/we": "We",
    "Driver": "GP"
  },
  {
    "Title": "Indescribable",
    "Themes/key words": "Creation",
    "Function/Emotion": "D: Expresses awe of creator",
    "Writer": "Reeves, Story",
    "Source": "WT",
    "Year": 2004,
    "Ideal Key(s)*": "D,E",
    "Tempo": 60,
    "Time": "6/8",
    "Range": 5,
    "Structure": "VCVCIC",
    "Style": "Driving",
    "Difficulty (vocal)": "Rhythm",
    "Addressed to": "God",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "Bless the Lord",
    "Themes/key words": "Worship, God�s goodness, eternity",
    "Function/Emotion": "D: Worship",
    "Writer": "Myrin, Redman",
    "Source": "WT",
    "Year": 2011,
    "Ideal Key(s)*": "D",
    "Tempo": 80,
    "Time": "4/4",
    "Range": 10,
    "Structure": "CVCVCVC",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Range",
    "Addressed to": "Self, God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Blessed be your name",
    "Themes/key words": "Suffering, blessing, worship, faithfulness",
    "Function/Emotion": "D/R: Worship in blessings and suffering",
    "Writer": "Redman",
    "Source": "ThankYou",
    "Year": 2002,
    "Ideal Key(s)*": "G",
    "Tempo": 116,
    "Time": "4/4",
    "Range": 10,
    "Structure": "VVCVVCBC",
    "Style": "Uplifting",
    "Difficulty (vocal)": "Rhythm, range",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "G"
  },
  {
    "Title": "Here I am to worship",
    "Themes/key words": "God exalted and humbled in Jesus, cross",
    "Function/Emotion": "D: Worship of exalted and humbled God",
    "Writer": "Hughes",
    "Source": "Thank You",
    "Year": 2000,
    "Ideal Key(s)*": "E",
    "Tempo": 80,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VCVCBC",
    "Style": "Reflective, uplifting",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "This is amazing grace",
    "Themes/key words": "King, grace, praise",
    "Function/Emotion": "D: Praise",
    "Writer": "Wickham, Riddle",
    "Source": "Bethel",
    "Year": 2012,
    "Ideal Key(s)*": "E, F",
    "Tempo": 108,
    "Time": "4/4",
    "Range": 6,
    "Structure": "VVCVVCBC",
    "Style": "Upbeat relaxed",
    "Difficulty (vocal)": "Rhythm",
    "Addressed to": "God",
    "I/we": "I",
    "Driver": "G"
  },
  {
    "Title": "Only a holy God",
    "Themes/key words": "Holy God, majesty, glory, power, Father",
    "Function/Emotion": "D/R: Worship of holy and personal God",
    "Writer": "Smith et al",
    "Source": "City Alight",
    "Year": 2016,
    "Ideal Key(s)*": "D",
    "Tempo": "150/50",
    "Time": "3/4",
    "Range": 9,
    "Structure": "VVCVCVC",
    "Style": "Reflective",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "I/we",
    "Driver": "PG"
  },
  {
    "Title": "Christ is mine forevermore",
    "Themes/key words": "Walking with Christ, guidance, suffering, reward",
    "Function/Emotion": "R: Comfort, assurance in walk with Christ",
    "Writer": "Robinson, Thompson",
    "Source": "City Alight",
    "Year": 2016,
    "Ideal Key(s)*": "Bb",
    "Tempo": 72,
    "Time": "3/4",
    "Range": 9,
    "Structure": "VVVB",
    "Style": "Modern hymn",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "P"
  },
  {
    "Title": "Ancient of Days",
    "Themes/key words": "Kingdom, worship of whole earth",
    "Function/Emotion": "D: Declaration of worship",
    "Writer": "Sadler, Harvill",
    "Source": "Integrity",
    "Year": 1992,
    "Ideal Key(s)*": "Bb",
    "Tempo": 88,
    "Time": "4/4",
    "Range": 10,
    "Structure": "VCVCBC",
    "Style": "Upbeat retro",
    "Difficulty (vocal)": "Range",
    "Addressed to": "God",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "He is exalted",
    "Themes/key words": "King, praise, truth, rejoice",
    "Function/Emotion": "D: Simple expression of worship",
    "Writer": "Paris",
    "Source": "",
    "Year": 1985,
    "Ideal Key(s)*": "D,E",
    "Tempo": "150/50",
    "Time": "6/8",
    "Range": 9,
    "Structure": "VC",
    "Style": "Retro",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Awesome God",
    "Themes/key words": "God reigns with wisdom, power, love",
    "Function/Emotion": "D/R: Good add-on to another song",
    "Writer": "Mullins",
    "Source": "",
    "Year": 1988,
    "Ideal Key(s)*": "E,F,G",
    "Tempo": 66,
    "Time": "4/4",
    "Range": 6,
    "Structure": "C",
    "Style": "Simple",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "The Servant King",
    "Themes/key words": "Jesus servant, cross, love, respond in obedience, serving others",
    "Function/Emotion": "R: Thankfulness, obedience, serving others",
    "Writer": "Kendrick",
    "Source": "Thankyou",
    "Year": 1983,
    "Ideal Key(s)*": "Eb",
    "Tempo": 65,
    "Time": "4/4",
    "Range": 9,
    "Structure": "VC x4",
    "Style": "Retro",
    "Difficulty (vocal)": "Moderate",
    "Addressed to": "God, others",
    "I/we": "I, we",
    "Driver": "P/G"
  },
  {
    "Title": "God of Wonders",
    "Themes/key words": "Creation, holy God",
    "Function/Emotion": "D: Worship of creator",
    "Writer": "Byrd, Hindalong",
    "Source": "",
    "Year": 2000,
    "Ideal Key(s)*": "F,G",
    "Tempo": 82,
    "Time": "4/4",
    "Range": 6,
    "Structure": "VCVC",
    "Style": "Relaxed",
    "Difficulty (vocal)": "Rhythm",
    "Addressed to": "God",
    "I/we": "We",
    "Driver": "G"
  },
  {
    "Title": "The steadfast love",
    "Themes/key words": "Love, mercies, faithfulness",
    "Function/Emotion": "D/R: Good add-on to another song",
    "Writer": "McNeill",
    "Source": "",
    "Year": 1974,
    "Ideal Key(s)*": "D,E",
    "Tempo": 80,
    "Time": "4/4",
    "Range": 9,
    "Structure": "C",
    "Style": "Reflective",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "I/we",
    "Driver": "PG"
  },
  {
    "Title": "Turn your eyes upon Jesus",
    "Themes/key words": "Jesus�s glory and grace",
    "Function/Emotion": "D/P: Good add-on to another song or prep",
    "Writer": "Lemmel",
    "Source": "New Spring",
    "Year": 1922,
    "Ideal Key(s)*": "C,D,Eb",
    "Tempo": 84,
    "Time": "3/4",
    "Range": 6,
    "Structure": "C",
    "Style": "Reflective",
    "Difficulty (vocal)": "Easy",
    "Addressed to": "All",
    "I/we": "I/we",
    "Driver": "PG"
  },
  {
    "Title": "Revelation song",
    "Themes/key words": "Holy God, powerful, Jesus as King (Revelation 4,5)",
    "Function/Emotion": "D: Praise of all powerful God and Lamb",
    "Writer": "Riddle",
    "Source": "Gateway",
    "Year": 2004,
    "Ideal Key(s)*": "C,D",
    "Tempo": 64,
    "Time": "4/4",
    "Range": 8,
    "Structure": "VVC",
    "Style": "Builds",
    "Difficulty (vocal)": "Verses don�t scan",
    "Addressed to": "All/God",
    "I/we": "I",
    "Driver": "PG"
  },
  {
    "Title": "Salvation belongs to our God",
    "Themes/key words": "Salvation, praise, glory, redeemed, unity",
    "Function/Emotion": "D: Praise, unity",
    "Writer": "Howard, Turner",
    "Source": "",
    "Year": 1985,
    "Ideal Key(s)*": "F,G",
    "Tempo": "",
    "Time": "4/4",
    "Range": 8,
    "Structure": "VCVC",
    "Style": "Retro",
    "Difficulty (vocal)": "Rhythm",
    "Addressed to": "Each other",
    "I/we": "We",
    "Driver": "PG"
  },
  {
    "Title": "",
    "Themes/key words": "",
    "Function/Emotion": "",
    "Writer": "",
    "Source": "",
    "Year": "",
    "Ideal Key(s)*": "",
    "Tempo": "",
    "Time": "",
    "Range": "",
    "Structure": "",
    "Style": "",
    "Difficulty (vocal)": "",
    "Addressed to": "",
    "I/we": "",
    "Driver": ""
  },
  {
    "Title": "",
    "Themes/key words": "",
    "Function/Emotion": "",
    "Writer": "",
    "Source": "",
    "Year": "",
    "Ideal Key(s)*": "",
    "Tempo": "",
    "Time": "",
    "Range": "",
    "Structure": "",
    "Style": "",
    "Difficulty (vocal)": "",
    "Addressed to": "",
    "I/we": "",
    "Driver": ""
  }
];
